# Generated by Django 2.2.12 on 2022-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='from_account',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='to_account',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
