# Generated by Django 2.2.12 on 2022-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220611_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(max_length=240, primary_key=True, serialize=False),
        ),
    ]
