# Generated by Django 2.2.12 on 2022-06-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
